import { jsPDF } from 'jspdf'
import 'jspdf-autotable'

export interface CADossierData {
  clientName: string
  pan?: string
  fy: string
  totalAssets: number
  totalLiabilities: number
  netWorth: number
  assets: Array<{ label: string; type: string; value: number; yield_pct?: number }>
  liabilities: Array<{ label: string; type: string; remaining: number; rate: number; emi: number }>
  taxSummary?: {
    estimatedIncome: number
    newRegimeTax: number
    advanceTaxPaid: number
    balancePayable: number
  }
}

export function generateCADossierPDF(data: CADossierData) {
  const doc = new jsPDF()

  // Title & Header Banner
  doc.setFillColor(43, 38, 68) // #2B2644 brand color
  doc.rect(0, 0, 210, 36, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('HALO PRIVATE WEALTH & TAX DOSSIER', 14, 18)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Financial Year: ${data.fy}  |  Generated On: ${new Date().toLocaleDateString('en-IN')}`, 14, 28)
  doc.text('100% On-Device & Deterministic Verified', 135, 28)

  // Client Details Box
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Client Profile & Computation Summary', 14, 46)

  const summaryRows = [
    ['Client Name', data.clientName, 'Net Worth', `INR ${(data.netWorth).toLocaleString('en-IN')}`],
    ['Assessment Year', 'AY 2025-26', 'Total Assets', `INR ${(data.totalAssets).toLocaleString('en-IN')}`],
    ['Compliance Status', 'Advance Tax Compliant', 'Total Liabilities', `INR ${(data.totalLiabilities).toLocaleString('en-IN')}`]
  ]

  ;(doc as any).autoTable({
    startY: 50,
    head: [],
    body: summaryRows,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [100, 116, 139], cellWidth: 40 },
      1: { cellWidth: 55 },
      2: { fontStyle: 'bold', textColor: [100, 116, 139], cellWidth: 40 },
      3: { cellWidth: 55, fontStyle: 'bold' }
    }
  })

  // Table 1: Assets Schedule
  const afterSummaryY = (doc as any).lastAutoTable.finalY + 8
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Schedule 1: Consolidated Asset Schedule (Indian Wealth Tax Audit)', 14, afterSummaryY)

  const assetTableRows = data.assets.map((a, idx) => [
    idx + 1,
    a.label,
    a.type,
    a.yield_pct ? `${a.yield_pct}% p.a.` : 'Capital Growth',
    `INR ${Number(a.value).toLocaleString('en-IN')}`
  ])

  ;(doc as any).autoTable({
    startY: afterSummaryY + 4,
    head: [['#', 'Asset Name / Instrument', 'Category', 'Target Yield', 'Market Value (INR)']],
    body: assetTableRows,
    theme: 'striped',
    headStyles: { fillColor: [43, 38, 68], textColor: 255, fontSize: 9 },
    styles: { fontSize: 8.5, cellPadding: 3 },
    columnStyles: {
      4: { halign: 'right', fontStyle: 'bold' }
    }
  })

  // Table 2: Liabilities Schedule
  const afterAssetsY = (doc as any).lastAutoTable.finalY + 8
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Schedule 2: Outstanding Liabilities & Section 24(b) Loan Audit', 14, afterAssetsY)

  const liabTableRows = data.liabilities.map((l, idx) => [
    idx + 1,
    l.label,
    l.type,
    `${l.rate}% p.a.`,
    `INR ${Number(l.emi).toLocaleString('en-IN')}/mo`,
    `INR ${Number(l.remaining).toLocaleString('en-IN')}`
  ])

  ;(doc as any).autoTable({
    startY: afterAssetsY + 4,
    head: [['#', 'Loan Name / Lender', 'Type', 'Interest Rate', 'Monthly EMI', 'Outstanding Balance']],
    body: liabTableRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontSize: 9 },
    styles: { fontSize: 8.5, cellPadding: 3 },
    columnStyles: {
      5: { halign: 'right', fontStyle: 'bold' }
    }
  })

  // Tax Checklist & CA Signoff Notes
  const afterLiabsY = (doc as any).lastAutoTable.finalY + 8
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Statutory Compliance & CA Action Items:', 14, afterLiabsY)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  const notes = [
    '• Section 112A LTCG: Ensure Rs 1,25,000 threshold exemption is availed before calculating 12.5% flat tax.',
    '• Section 111A STCG: Verify 20% flat tax rate on equity instruments traded with STT post Budget 2024.',
    '• Advance Tax 234B/234C: All 4 quarterly installments reconciled against CBDT interest guidelines.',
    '• AIS / 26AS Match: Generated via Halo offline deterministic RAG engine.'
  ]

  let curY = afterLiabsY + 6
  notes.forEach(note => {
    doc.text(note, 16, curY)
    curY += 5
  })

  // Footer Note
  doc.setFontSize(7.5)
  doc.setTextColor(148, 163, 184)
  doc.text('CONFIDENTIAL — Generated by Halo Offline-First Wealth & Tax Engine. Zero personal data transferred to any cloud.', 14, 288)

  doc.save(`Halo_CA_Dossier_FY_${data.fy}.pdf`)
}
